2025-10-15 23:21:39,044 - MainThread - sqlmesh.core.config.connection - INFO - Creating new DuckDB adapter for in-memory database (connection.py:493)
2025-10-15 23:21:39,170 - MainThread - sqlmesh.core.config.connection - INFO - Creating new DuckDB adapter for data files: {'local.duckdb'} (connection.py:491)
2025-10-15 23:21:39,170 - MainThread - sqlmesh.core.console - WARNING - The duckdb engine is not recommended for storing SQLMesh state in production deployments. Please see https://sqlmesh.readthedocs.io/en/stable/guides/configuration/#state-connection for a list of recommended engines and more information. (console.py:2335)
2025-10-15 23:21:39,230 - MainThread - sqlmesh.core.state_sync.db.migrator - INFO - Applying migration <module 'sqlmesh.migrations.v0000_baseline' from '/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/migrations/v0000_baseline.py'> (migrator.py:185)
2025-10-15 23:21:39,257 - MainThread - sqlmesh.core.state_sync.db.migrator - INFO - Applying migration <module 'sqlmesh.migrations.v0061_mysql_fix_blob_text_type' from '/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/migrations/v0061_mysql_fix_blob_text_type.py'> (migrator.py:185)
2025-10-15 23:21:39,257 - MainThread - sqlmesh.core.state_sync.db.migrator - INFO - Applying migration <module 'sqlmesh.migrations.v0062_add_model_gateway' from '/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/migrations/v0062_add_model_gateway.py'> (migrator.py:185)
2025-10-15 23:21:39,257 - MainThread - sqlmesh.core.state_sync.db.migrator - INFO - Applying migration <module 'sqlmesh.migrations.v0063_change_signals' from '/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/migrations/v0063_change_signals.py'> (migrator.py:185)
2025-10-15 23:21:39,257 - MainThread - sqlmesh.core.state_sync.db.migrator - INFO - Applying migration <module 'sqlmesh.migrations.v0064_join_when_matched_strings' from '/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/migrations/v0064_join_when_matched_strings.py'> (migrator.py:185)
2025-10-15 23:21:39,257 - MainThread - sqlmesh.core.state_sync.db.migrator - INFO - Applying migration <module 'sqlmesh.migrations.v0065_add_model_optimize' from '/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/migrations/v0065_add_model_optimize.py'> (migrator.py:185)
2025-10-15 23:21:39,257 - MainThread - sqlmesh.core.state_sync.db.migrator - INFO - Applying migration <module 'sqlmesh.migrations.v0066_add_auto_restatements' from '/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/migrations/v0066_add_auto_restatements.py'> (migrator.py:185)
2025-10-15 23:21:39,266 - MainThread - sqlmesh.core.state_sync.db.migrator - INFO - Applying migration <module 'sqlmesh.migrations.v0067_add_tsql_date_full_precision' from '/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/migrations/v0067_add_tsql_date_full_precision.py'> (migrator.py:185)
2025-10-15 23:21:39,266 - MainThread - sqlmesh.core.state_sync.db.migrator - INFO - Applying migration <module 'sqlmesh.migrations.v0068_include_unrendered_query_in_metadata_hash' from '/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/migrations/v0068_include_unrendered_query_in_metadata_hash.py'> (migrator.py:185)
2025-10-15 23:21:39,266 - MainThread - sqlmesh.core.state_sync.db.migrator - INFO - Applying migration <module 'sqlmesh.migrations.v0069_update_dev_table_suffix' from '/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/migrations/v0069_update_dev_table_suffix.py'> (migrator.py:185)
2025-10-15 23:21:39,267 - MainThread - sqlmesh.core.state_sync.db.migrator - INFO - Applying migration <module 'sqlmesh.migrations.v0070_include_grains_in_metadata_hash' from '/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/migrations/v0070_include_grains_in_metadata_hash.py'> (migrator.py:185)
2025-10-15 23:21:39,267 - MainThread - sqlmesh.core.state_sync.db.migrator - INFO - Applying migration <module 'sqlmesh.migrations.v0071_add_dev_version_to_intervals' from '/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/migrations/v0071_add_dev_version_to_intervals.py'> (migrator.py:185)
2025-10-15 23:21:39,269 - MainThread - sqlmesh.core.state_sync.db.migrator - INFO - Applying migration <module 'sqlmesh.migrations.v0072_add_environment_statements' from '/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/migrations/v0072_add_environment_statements.py'> (migrator.py:185)
2025-10-15 23:21:39,275 - MainThread - sqlmesh.core.state_sync.db.migrator - INFO - Applying migration <module 'sqlmesh.migrations.v0073_remove_symbolic_disable_restatement' from '/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/migrations/v0073_remove_symbolic_disable_restatement.py'> (migrator.py:185)
2025-10-15 23:21:39,275 - MainThread - sqlmesh.core.state_sync.db.migrator - INFO - Applying migration <module 'sqlmesh.migrations.v0074_add_partition_by_time_column_property' from '/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/migrations/v0074_add_partition_by_time_column_property.py'> (migrator.py:185)
2025-10-15 23:21:39,275 - MainThread - sqlmesh.core.state_sync.db.migrator - INFO - Applying migration <module 'sqlmesh.migrations.v0075_remove_validate_query' from '/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/migrations/v0075_remove_validate_query.py'> (migrator.py:185)
2025-10-15 23:21:39,275 - MainThread - sqlmesh.core.state_sync.db.migrator - INFO - Applying migration <module 'sqlmesh.migrations.v0076_add_cron_tz' from '/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/migrations/v0076_add_cron_tz.py'> (migrator.py:185)
2025-10-15 23:21:39,275 - MainThread - sqlmesh.core.state_sync.db.migrator - INFO - Applying migration <module 'sqlmesh.migrations.v0077_fix_column_type_hash_calculation' from '/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/migrations/v0077_fix_column_type_hash_calculation.py'> (migrator.py:185)
2025-10-15 23:21:39,275 - MainThread - sqlmesh.core.state_sync.db.migrator - INFO - Applying migration <module 'sqlmesh.migrations.v0078_warn_if_non_migratable_python_env' from '/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/migrations/v0078_warn_if_non_migratable_python_env.py'> (migrator.py:185)
2025-10-15 23:21:39,275 - MainThread - sqlmesh.core.state_sync.db.migrator - INFO - Applying migration <module 'sqlmesh.migrations.v0079_add_gateway_managed_property' from '/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/migrations/v0079_add_gateway_managed_property.py'> (migrator.py:185)
2025-10-15 23:21:39,279 - MainThread - sqlmesh.core.state_sync.db.migrator - INFO - Applying migration <module 'sqlmesh.migrations.v0080_add_batch_size_to_scd_type_2_models' from '/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/migrations/v0080_add_batch_size_to_scd_type_2_models.py'> (migrator.py:185)
2025-10-15 23:21:39,279 - MainThread - sqlmesh.core.state_sync.db.migrator - INFO - Applying migration <module 'sqlmesh.migrations.v0081_update_partitioned_by' from '/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/migrations/v0081_update_partitioned_by.py'> (migrator.py:185)
2025-10-15 23:21:39,279 - MainThread - sqlmesh.core.state_sync.db.migrator - INFO - Applying migration <module 'sqlmesh.migrations.v0082_warn_if_incorrectly_duplicated_statements' from '/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/migrations/v0082_warn_if_incorrectly_duplicated_statements.py'> (migrator.py:185)
2025-10-15 23:21:39,279 - MainThread - sqlmesh.core.state_sync.db.migrator - INFO - Applying migration <module 'sqlmesh.migrations.v0083_use_sql_for_scd_time_data_type_data_hash' from '/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/migrations/v0083_use_sql_for_scd_time_data_type_data_hash.py'> (migrator.py:185)
2025-10-15 23:21:39,279 - MainThread - sqlmesh.core.state_sync.db.migrator - INFO - Applying migration <module 'sqlmesh.migrations.v0084_normalize_quote_when_matched_and_merge_filter' from '/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/migrations/v0084_normalize_quote_when_matched_and_merge_filter.py'> (migrator.py:185)
2025-10-15 23:21:39,279 - MainThread - sqlmesh.core.state_sync.db.migrator - INFO - Applying migration <module 'sqlmesh.migrations.v0085_deterministic_repr' from '/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/migrations/v0085_deterministic_repr.py'> (migrator.py:185)
2025-10-15 23:21:39,279 - MainThread - sqlmesh.core.state_sync.db.migrator - INFO - Applying migration <module 'sqlmesh.migrations.v0086_check_deterministic_bug' from '/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/migrations/v0086_check_deterministic_bug.py'> (migrator.py:185)
2025-10-15 23:21:39,279 - MainThread - sqlmesh.core.state_sync.db.migrator - INFO - Applying migration <module 'sqlmesh.migrations.v0087_normalize_blueprint_variables' from '/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/migrations/v0087_normalize_blueprint_variables.py'> (migrator.py:185)
2025-10-15 23:21:39,279 - MainThread - sqlmesh.core.state_sync.db.migrator - INFO - Applying migration <module 'sqlmesh.migrations.v0088_warn_about_variable_python_env_diffs' from '/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/migrations/v0088_warn_about_variable_python_env_diffs.py'> (migrator.py:185)
2025-10-15 23:21:39,279 - MainThread - sqlmesh.core.state_sync.db.migrator - INFO - Applying migration <module 'sqlmesh.migrations.v0089_add_virtual_environment_mode' from '/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/migrations/v0089_add_virtual_environment_mode.py'> (migrator.py:185)
2025-10-15 23:21:39,279 - MainThread - sqlmesh.core.state_sync.db.migrator - INFO - Applying migration <module 'sqlmesh.migrations.v0090_add_forward_only_column' from '/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/migrations/v0090_add_forward_only_column.py'> (migrator.py:185)
2025-10-15 23:21:39,282 - MainThread - sqlmesh.core.state_sync.db.migrator - INFO - Applying migration <module 'sqlmesh.migrations.v0091_on_additive_change' from '/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/migrations/v0091_on_additive_change.py'> (migrator.py:185)
2025-10-15 23:21:39,282 - MainThread - sqlmesh.core.state_sync.db.migrator - INFO - Applying migration <module 'sqlmesh.migrations.v0092_warn_about_dbt_data_type_diff' from '/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/migrations/v0092_warn_about_dbt_data_type_diff.py'> (migrator.py:185)
2025-10-15 23:21:39,282 - MainThread - sqlmesh.core.state_sync.db.migrator - INFO - Applying migration <module 'sqlmesh.migrations.v0093_use_raw_sql_in_fingerprint' from '/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/migrations/v0093_use_raw_sql_in_fingerprint.py'> (migrator.py:185)
2025-10-15 23:21:39,282 - MainThread - sqlmesh.core.state_sync.db.migrator - INFO - Applying migration <module 'sqlmesh.migrations.v0094_add_dev_version_and_fingerprint_columns' from '/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/migrations/v0094_add_dev_version_and_fingerprint_columns.py'> (migrator.py:185)
2025-10-15 23:21:39,288 - MainThread - sqlmesh.core.state_sync.db.migrator - INFO - Applying migration <module 'sqlmesh.migrations.v0095_warn_about_dbt_raw_sql_diff' from '/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/migrations/v0095_warn_about_dbt_raw_sql_diff.py'> (migrator.py:185)
2025-10-15 23:21:39,288 - MainThread - sqlmesh.core.state_sync.db.migrator - INFO - Applying migration <module 'sqlmesh.migrations.v0096_remove_plan_dags_table' from '/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/migrations/v0096_remove_plan_dags_table.py'> (migrator.py:185)
2025-10-15 23:21:39,288 - MainThread - sqlmesh.core.state_sync.db.migrator - INFO - Applying migration <module 'sqlmesh.migrations.v0097_add_dbt_name_in_node' from '/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/migrations/v0097_add_dbt_name_in_node.py'> (migrator.py:185)
2025-10-15 23:21:39,289 - MainThread - sqlmesh.core.state_sync.db.migrator - INFO - Applying migration <module 'sqlmesh.migrations.v0098_add_dbt_node_info_in_node' from '/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/migrations/v0098_add_dbt_node_info_in_node.py'> (migrator.py:185)
2025-10-15 23:21:39,289 - MainThread - sqlmesh.core.state_sync.db.migrator - INFO - Applying migration <module 'sqlmesh.migrations.v0099_add_last_altered_to_intervals' from '/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/migrations/v0099_add_last_altered_to_intervals.py'> (migrator.py:185)
2025-10-15 23:21:39,291 - MainThread - sqlmesh.core.state_sync.db.migrator - INFO - Applying migration <module 'sqlmesh.migrations.v0100_add_grants_and_grants_target_layer' from '/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/migrations/v0100_add_grants_and_grants_target_layer.py'> (migrator.py:185)
2025-10-15 23:21:39,292 - MainThread - sqlmesh.core.state_sync.db.migrator - INFO - Fetching environments (migrator.py:207)
2025-10-15 23:21:39,294 - MainThread - sqlmesh.core.state_sync.db.migrator - INFO - Migrating snapshot rows... (migrator.py:224)
2025-10-15 23:21:39,297 - MainThread - sqlmesh.core.state_sync.db.migrator - INFO - No changes to snapshots detected (migrator.py:217)
2025-10-15 23:21:53,270 - MainThread - sqlmesh.core.plan.evaluator - INFO - Evaluating plan stage CreateSnapshotRecordsStage (evaluator.py:123)
2025-10-15 23:21:53,297 - MainThread - sqlmesh.core.plan.evaluator - INFO - Evaluating plan stage PhysicalLayerSchemaCreationStage (evaluator.py:123)
2025-10-15 23:21:53,299 - MainThread - sqlmesh.core.snapshot.evaluator - INFO - Creating schema 'sqlmesh__sqlmesh_example' (evaluator.py:1443)
2025-10-15 23:21:53,299 - MainThread - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: /* SQLMESH_PLAN: 99f5bb231640402ea1916c4ed2bda992 */ CREATE DATABASE IF NOT EXISTS "sqlmesh__sqlmesh_example" (base.py:2614)
2025-10-15 23:21:53,309 - MainThread - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7828269b10>: Failed to establish a new connection: [Errno 111] Connection refused')': /? (connectionpool.py:868)
2025-10-15 23:21:53,319 - MainThread - clickhouse_connect.driver.httpclient - WARNING - Unexpected Http Driver Exception (httpclient.py:532)
2025-10-15 23:21:53,319 - MainThread - sqlmesh.core.engine_adapter.base - WARNING - Failed to create database 'sqlmesh__sqlmesh_example': Error HTTPConnectionPool(host='81.177.175.49', port=8123): Max retries exceeded with url: /? (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f781a38ec10>: Failed to establish a new connection: [Errno 111] Connection refused')) executing HTTP request attempt 1 (http://81.177.175.49:8123) (base.py:1410)
2025-10-15 23:21:53,319 - MainThread - sqlmesh.core.plan.evaluator - INFO - Evaluating plan stage BackfillStage (evaluator.py:123)
2025-10-15 23:21:53,327 - MainThread - sqlmesh.core.snapshot.evaluator - INFO - Listing data objects in schema sqlmesh__sqlmesh_example (evaluator.py:1610)
2025-10-15 23:21:53,338 - MainThread - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f781a444890>: Failed to establish a new connection: [Errno 111] Connection refused')': /? (connectionpool.py:868)
2025-10-15 23:21:53,347 - MainThread - clickhouse_connect.driver.httpclient - WARNING - Unexpected Http Driver Exception (httpclient.py:532)
2025-10-15 23:21:53,357 - MainThread - sqlmesh.core.context - INFO - Plan application failed. (context.py:1763)
Traceback (most recent call last):
  File "/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 493, in _make_request
    conn.request(
  File "/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/urllib3/connection.py", line 494, in request
    self.endheaders()
  File "/usr/lib/python3.11/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.11/http/client.py", line 975, in send
    self.connect()
  File "/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/urllib3/connection.py", line 325, in connect
    self.sock = self._new_conn()
                ^^^^^^^^^^^^^^^^
  File "/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/urllib3/connection.py", line 213, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f781a445250>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/clickhouse_connect/driver/httpclient.py", line 522, in _raw_request
    response = self.http.request(method, url, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/urllib3/_request_methods.py", line 143, in request
    return self.request_encode_body(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/urllib3/_request_methods.py", line 278, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/urllib3/poolmanager.py", line 459, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='81.177.175.49', port=8123): Max retries exceeded with url: /? (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f781a445250>: Failed to establish a new connection: [Errno 111] Connection refused'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/core/context.py", line 1755, in apply
    self._apply(plan, circuit_breaker)
  File "/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/core/context.py", line 2547, in _apply
    self._scheduler.create_plan_evaluator(self).evaluate(
  File "/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/core/plan/evaluator.py", line 105, in evaluate
    self._evaluate_stages(plan_stages, plan)
  File "/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/core/plan/evaluator.py", line 125, in _evaluate_stages
    handler(stage, plan)
  File "/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/core/plan/evaluator.py", line 249, in visit_backfill_stage
    errors, _ = scheduler.run_merged_intervals(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/core/scheduler.py", line 502, in run_merged_intervals
    for s in self.snapshot_evaluator.get_snapshots_to_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/core/snapshot/evaluator.py", line 432, in get_snapshots_to_create
    existing_data_objects = self._get_physical_data_objects(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/core/snapshot/evaluator.py", line 1540, in _get_physical_data_objects
    return self._get_data_objects(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/core/snapshot/evaluator.py", line 1621, in _get_data_objects
    for objs in concurrent_apply_to_values(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/utils/concurrency.py", line 264, in concurrent_apply_to_values
    return [fn(value) for value in values]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/utils/concurrency.py", line 264, in <listcomp>
    return [fn(value) for value in values]
            ^^^^^^^^^
  File "/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/core/snapshot/evaluator.py", line 1623, in <lambda>
    lambda s: _get_data_objects_in_schema(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/core/snapshot/evaluator.py", line 1611, in _get_data_objects_in_schema
    return self.get_adapter(gateway).get_data_objects(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/core/engine_adapter/shared.py", line 335, in internal_wrapper
    return func(*list_args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/core/engine_adapter/base.py", line 2343, in get_data_objects
    objects = self._get_data_objects(schema_name, set(batch))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/core/engine_adapter/clickhouse.py", line 155, in _get_data_objects
    df = self.fetchdf(query)
         ^^^^^^^^^^^^^^^^^^^
  File "/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/core/engine_adapter/base.py", line 2428, in fetchdf
    df = self._fetch_native_df(query, quote_identifiers=quote_identifiers)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/core/engine_adapter/clickhouse.py", line 83, in _fetch_native_df
    return self.cursor.client.query_df(
           ^^^^^^^^^^^
  File "/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/core/engine_adapter/base.py", line 195, in cursor
    return self._connection_pool.get_cursor()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/utils/connection_pool.py", line 289, in get_cursor
    self._cursor = self.get().cursor()
                   ^^^^^^^^^^
  File "/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/sqlmesh/utils/connection_pool.py", line 296, in get
    self._connection = self._connection_factory()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/clickhouse_connect/dbapi/__init__.py", line 22, in connect
    return Connection(host=host,
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/clickhouse_connect/dbapi/connection.py", line 23, in __init__
    self.client = create_client(host=host,
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/clickhouse_connect/driver/__init__.py", line 125, in create_client
    return HttpClient(interface, host, port, username, password, database, access_token,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/clickhouse_connect/driver/httpclient.py", line 174, in __init__
    super().__init__(database=database,
  File "/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/clickhouse_connect/driver/client.py", line 71, in __init__
    self._init_common_settings(apply_server_timezone)
  File "/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/clickhouse_connect/driver/client.py", line 76, in _init_common_settings
    tuple(self.command('SELECT version(), timezone()', use_database=False))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/clickhouse_connect/driver/httpclient.py", line 412, in command
    response = self._raw_request(payload, params, headers, method, fields=fields, server_wait=False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ddich/projects/sqlmesh/.venv/lib/python3.11/site-packages/clickhouse_connect/driver/httpclient.py", line 534, in _raw_request
    raise OperationalError(f'Error {ex} executing HTTP request attempt {attempts}{err_url}') from ex
clickhouse_connect.driver.exceptions.OperationalError: Error HTTPConnectionPool(host='81.177.175.49', port=8123): Max retries exceeded with url: /? (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f781a445250>: Failed to establish a new connection: [Errno 111] Connection refused')) executing HTTP request attempt 1 (http://81.177.175.49:8123)
2025-10-15 23:21:54,149 - MainThread - root - INFO - Shutting down the event dispatcher (dispatcher.py:159)
